version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: secure_wallet_pg
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=wallet_admin
      - POSTGRES_PASSWORD=wallet_admin
      - POSTGRES_DB=secure_wallet
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: